export const TRANSPORTORDER = {
    TRANSPORTORDER: "TRANSPORTORDER",
    SETTRANSPORTORDER: "SETTRANSPORTORDER",
    COMPANY: "COMPANY",
    UPDATE: "UPDATE",
    ERROR: "ERROR",
    LOADING: "LOADING",
    DELETEFILTER: "DELETEFILTER",
    ORDERSTATE: "ORDERSTATE",
  };
  export const ORDERLINE = {
    ORDERLINE: "ORDERLINE",
    SETORDERLINE: "SETORDERLINE",
    DOCUMENTATION: "DOCUMENTATION",
    SETDOCUMENTATION: "SETDOCUMENTATION",
    ERROR: "ERROR",
    UPDATE: "UPDATE",
    LOADING: "LOADING",
    ORDERSTATE: "ORDERSTATE",
  };
  