// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/user/app-delivery-v2/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/user/app-delivery-v2/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('app-delivery-v2', appParameters);
});
require('/home/user/app-delivery-v2/index.android.js');